# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e4ca17da9da034851e7cf18fc9986d40d92961ab235fb3c38fb62685b40e1677d4a45d25a855826aa25c56ea102db5d8184331a3565395e304976739b6e115

test:
  secret_key_base: 441422f6f9a84df1099fabdc05d6b66cd6f01fa57a190166473524ff72d7cc0da2b95868099bd71151650f436cccbfa8fddb69ea771d460f650fc7fb41445da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
